- name: Create  VM
  hosts: localhost
  connection: local
  vars_files:
  - vars.yaml
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{MyRg}}"
      location: westeurope
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{MyRg}}"
      name: "{{MyVnet}}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{MyRg}}"
      name: "{{MySubnet}}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{MyVnet}}"
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{MyRg}}"
      name: "{{MyNsg}}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1002
          direction: Inbound
  - include_tasks: vm_details.yaml
    loop:
    - { name: 'one', tag: 'haproxy' }
    - { name: 'two', tag: 'apache' }
    - { name: 'tres', tag: 'apache' }
    loop_control:
      loop_var: vm

- include: apache.yaml
- include: haproxy.yaml
