- name: Create  VM
  hosts: localhost
  connection: local
  vars:
    MyRg: table5jdlab
    MyVnet: table5jdvnet
    MySubnet: table5jdsubnet
    MyVm: table5jdvm1
    MyNic: table5jdnic
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{MyRg}}"
      location: westeurope
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{MyRg}}"
      name: "{{MyVnet}}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{MyRg}}"
      name: "{{MySubnet}}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{MyVnet}}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{MyRg}}"
      allocation_method: Static
      name: table5jdPubIp
    register: output_ip_address
  - name: Output public IP 
    debug:
      msg: "Public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{MyRg}}"
      name: table5jdnsggroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{MyRg}}"
      name: "{{MyNic}}"
      virtual_network: "{{MyVnet}}"
      subnet: "{{MySubnet}}"
      public_ip_name: table5jdPubIp
      security_group: table5jdnsggroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{MyRg}}"
      name: "{{MyVm}}"
      vm_size: Standard_DS1_v2
      admin_username: azureops
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureops/.ssh/authorized_keys
          key_data: |
            {{lookup('file', '/home/azureops/.ssh/id_rsa.pub')}}
      network_interfaces: "{{MyNic}}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
